"""Title-slide motif: the pilot's 10 x 10 scan as a bare grid, derived from the frozen heat map asset.
Writes assets/2026-09-16-200514/title-grid.tex: TikZ path commands only, one unit per cell, origin top left.
Usage: python3 build_title_grid.py"""
import re
from pathlib import Path

A = Path(__file__).parent / "assets" / "2026-09-16-200514"
cells, cur = [], None
for line in (A / "pilot-heatmap.tex").read_text().splitlines():
    m = re.match(r"\\path\[fill=scanHigh!(\d+)!white.*?\] \((\d+),(-?\d+)\) rectangle", line)
    if m:
        cur = {"pct": int(m.group(1)), "x": int(m.group(2)), "y": int(m.group(3)), "inv": False, "acc": False}
        cells.append(cur); continue
    if cur and line.startswith("\\draw[black,line width=0.85pt]"):
        cur["inv"] = True
    if cur and "$\\star$" in line:
        cur["acc"] = True
assert len(cells) == 100, len(cells)
out = ["% generated by build_title_grid.py from pilot-heatmap.tex; do not edit"]
for c in cells:
    x, y = c["x"], c["y"]                       # y is the bottom edge of the cell in the source: -1 for the first row
    shade = f"Teal!{min(100, 10 + round(0.9 * c['pct']))}!Paper" if c["pct"] else "Ink!6!Paper"
    out.append(f"\\fill[{shade},rounded corners=.5pt] ({x + .07:.2f},{y + .07:.2f}) rectangle ({x + .93:.2f},{y + .93:.2f});")
    if c["inv"]:
        out.append(f"\\draw[Ink,line width=.7pt,rounded corners=.5pt] ({x + .07:.2f},{y + .07:.2f}) rectangle ({x + .93:.2f},{y + .93:.2f});")
    if c["acc"]:
        out.append(f"\\fill[Rust] ({x + .5:.2f},{y + .5:.2f}) circle (.17);")
(A / "title-grid.tex").write_text("\n".join(out) + "\n")
print("cells", len(cells), "investigated", sum(c["inv"] for c in cells), "accepted", sum(c["acc"] for c in cells))
